chore: update to newest version of each submodule
free5gc/free5gc pull request #633
Opened 2024-12-28 12:53 UTC by Alonza0314

Update all submodules to newest version.

2024-12-28 14:40 UTC, andy89923 commented
Hi @Alonza0314 ,

You need to enter `test/` and run `go mod tidy`.

2024-12-28 14:44 UTC, Alonza0314 commented
> Hi @Alonza0314 ,
> 
> You need to enter `test/` and run `go mod tidy`.

Oh! I see, that's exactly what I’m working on right now.

2024-12-29 08:02 UTC, andy89923 commented on test/go.mod
I suggest updating `golang.org/x/net` to v0.33.0 as well.

2024-12-29 16:46 UTC, andy89923 requested changes
Suggest to bump submodules' `net` package version.

2025-01-02 15:03 UTC, andy89923 approved these changes
LGTM!

2025-01-03 08:40 UTC, ianchen0119 approved these changes

2025-01-03 08:41 UTC, merged